[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dimensionless-wildfire"
version = "1.0"

[tool.setuptools]
packages = ["data", "models", "training", "notebooks"]
